/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleTopologyRouteImport } from './routes/_authenticated/console.topology'
import { Route as AuthenticatedConsoleSustainabilityRouteImport } from './routes/_authenticated/console.sustainability'
import { Route as AuthenticatedConsoleSettingsRouteImport } from './routes/_authenticated/console.settings'
import { Route as AuthenticatedConsoleResponsibleAiRouteImport } from './routes/_authenticated/console.responsible-ai'
import { Route as AuthenticatedConsolePredictionsRouteImport } from './routes/_authenticated/console.predictions'
import { Route as AuthenticatedConsoleKnowledgeRouteImport } from './routes/_authenticated/console.knowledge'
import { Route as AuthenticatedConsoleIntelligenceRouteImport } from './routes/_authenticated/console.intelligence'
import { Route as AuthenticatedConsoleIncidentsRouteImport } from './routes/_authenticated/console.incidents'
import { Route as AuthenticatedConsoleDevicesRouteImport } from './routes/_authenticated/console.devices'
import { Route as AuthenticatedConsoleCopilotRouteImport } from './routes/_authenticated/console.copilot'
import { Route as AuthenticatedConsoleAuditRouteImport } from './routes/_authenticated/console.audit'
import { Route as AuthenticatedConsoleAboutRouteImport } from './routes/_authenticated/console.about'
import { Route as AuthenticatedConsoleIncidentsIncidentIdRouteImport } from './routes/_authenticated/console.incidents.$incidentId'
import { Route as AuthenticatedConsoleDevicesDeviceIdRouteImport } from './routes/_authenticated/console.devices.$deviceId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTopologyRoute =
  AuthenticatedConsoleTopologyRouteImport.update({
    id: '/topology',
    path: '/topology',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSustainabilityRoute =
  AuthenticatedConsoleSustainabilityRouteImport.update({
    id: '/sustainability',
    path: '/sustainability',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSettingsRoute =
  AuthenticatedConsoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleResponsibleAiRoute =
  AuthenticatedConsoleResponsibleAiRouteImport.update({
    id: '/responsible-ai',
    path: '/responsible-ai',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePredictionsRoute =
  AuthenticatedConsolePredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleKnowledgeRoute =
  AuthenticatedConsoleKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleIntelligenceRoute =
  AuthenticatedConsoleIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleIncidentsRoute =
  AuthenticatedConsoleIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleDevicesRoute =
  AuthenticatedConsoleDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCopilotRoute =
  AuthenticatedConsoleCopilotRouteImport.update({
    id: '/copilot',
    path: '/copilot',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleAuditRoute =
  AuthenticatedConsoleAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleAboutRoute =
  AuthenticatedConsoleAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleIncidentsIncidentIdRoute =
  AuthenticatedConsoleIncidentsIncidentIdRouteImport.update({
    id: '/$incidentId',
    path: '/$incidentId',
    getParentRoute: () => AuthenticatedConsoleIncidentsRoute,
  } as any)
const AuthenticatedConsoleDevicesDeviceIdRoute =
  AuthenticatedConsoleDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => AuthenticatedConsoleDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/console/about': typeof AuthenticatedConsoleAboutRoute
  '/console/audit': typeof AuthenticatedConsoleAuditRoute
  '/console/copilot': typeof AuthenticatedConsoleCopilotRoute
  '/console/devices': typeof AuthenticatedConsoleDevicesRouteWithChildren
  '/console/incidents': typeof AuthenticatedConsoleIncidentsRouteWithChildren
  '/console/intelligence': typeof AuthenticatedConsoleIntelligenceRoute
  '/console/knowledge': typeof AuthenticatedConsoleKnowledgeRoute
  '/console/predictions': typeof AuthenticatedConsolePredictionsRoute
  '/console/responsible-ai': typeof AuthenticatedConsoleResponsibleAiRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/sustainability': typeof AuthenticatedConsoleSustainabilityRoute
  '/console/topology': typeof AuthenticatedConsoleTopologyRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/devices/$deviceId': typeof AuthenticatedConsoleDevicesDeviceIdRoute
  '/console/incidents/$incidentId': typeof AuthenticatedConsoleIncidentsIncidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/console/about': typeof AuthenticatedConsoleAboutRoute
  '/console/audit': typeof AuthenticatedConsoleAuditRoute
  '/console/copilot': typeof AuthenticatedConsoleCopilotRoute
  '/console/devices': typeof AuthenticatedConsoleDevicesRouteWithChildren
  '/console/incidents': typeof AuthenticatedConsoleIncidentsRouteWithChildren
  '/console/intelligence': typeof AuthenticatedConsoleIntelligenceRoute
  '/console/knowledge': typeof AuthenticatedConsoleKnowledgeRoute
  '/console/predictions': typeof AuthenticatedConsolePredictionsRoute
  '/console/responsible-ai': typeof AuthenticatedConsoleResponsibleAiRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/sustainability': typeof AuthenticatedConsoleSustainabilityRoute
  '/console/topology': typeof AuthenticatedConsoleTopologyRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/devices/$deviceId': typeof AuthenticatedConsoleDevicesDeviceIdRoute
  '/console/incidents/$incidentId': typeof AuthenticatedConsoleIncidentsIncidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/console/about': typeof AuthenticatedConsoleAboutRoute
  '/_authenticated/console/audit': typeof AuthenticatedConsoleAuditRoute
  '/_authenticated/console/copilot': typeof AuthenticatedConsoleCopilotRoute
  '/_authenticated/console/devices': typeof AuthenticatedConsoleDevicesRouteWithChildren
  '/_authenticated/console/incidents': typeof AuthenticatedConsoleIncidentsRouteWithChildren
  '/_authenticated/console/intelligence': typeof AuthenticatedConsoleIntelligenceRoute
  '/_authenticated/console/knowledge': typeof AuthenticatedConsoleKnowledgeRoute
  '/_authenticated/console/predictions': typeof AuthenticatedConsolePredictionsRoute
  '/_authenticated/console/responsible-ai': typeof AuthenticatedConsoleResponsibleAiRoute
  '/_authenticated/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/_authenticated/console/sustainability': typeof AuthenticatedConsoleSustainabilityRoute
  '/_authenticated/console/topology': typeof AuthenticatedConsoleTopologyRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/devices/$deviceId': typeof AuthenticatedConsoleDevicesDeviceIdRoute
  '/_authenticated/console/incidents/$incidentId': typeof AuthenticatedConsoleIncidentsIncidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/console'
    | '/console/about'
    | '/console/audit'
    | '/console/copilot'
    | '/console/devices'
    | '/console/incidents'
    | '/console/intelligence'
    | '/console/knowledge'
    | '/console/predictions'
    | '/console/responsible-ai'
    | '/console/settings'
    | '/console/sustainability'
    | '/console/topology'
    | '/console/'
    | '/console/devices/$deviceId'
    | '/console/incidents/$incidentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/console/about'
    | '/console/audit'
    | '/console/copilot'
    | '/console/devices'
    | '/console/incidents'
    | '/console/intelligence'
    | '/console/knowledge'
    | '/console/predictions'
    | '/console/responsible-ai'
    | '/console/settings'
    | '/console/sustainability'
    | '/console/topology'
    | '/console'
    | '/console/devices/$deviceId'
    | '/console/incidents/$incidentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/console'
    | '/_authenticated/console/about'
    | '/_authenticated/console/audit'
    | '/_authenticated/console/copilot'
    | '/_authenticated/console/devices'
    | '/_authenticated/console/incidents'
    | '/_authenticated/console/intelligence'
    | '/_authenticated/console/knowledge'
    | '/_authenticated/console/predictions'
    | '/_authenticated/console/responsible-ai'
    | '/_authenticated/console/settings'
    | '/_authenticated/console/sustainability'
    | '/_authenticated/console/topology'
    | '/_authenticated/console/'
    | '/_authenticated/console/devices/$deviceId'
    | '/_authenticated/console/incidents/$incidentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/topology': {
      id: '/_authenticated/console/topology'
      path: '/topology'
      fullPath: '/console/topology'
      preLoaderRoute: typeof AuthenticatedConsoleTopologyRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/sustainability': {
      id: '/_authenticated/console/sustainability'
      path: '/sustainability'
      fullPath: '/console/sustainability'
      preLoaderRoute: typeof AuthenticatedConsoleSustainabilityRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/settings': {
      id: '/_authenticated/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/responsible-ai': {
      id: '/_authenticated/console/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/console/responsible-ai'
      preLoaderRoute: typeof AuthenticatedConsoleResponsibleAiRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/predictions': {
      id: '/_authenticated/console/predictions'
      path: '/predictions'
      fullPath: '/console/predictions'
      preLoaderRoute: typeof AuthenticatedConsolePredictionsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/knowledge': {
      id: '/_authenticated/console/knowledge'
      path: '/knowledge'
      fullPath: '/console/knowledge'
      preLoaderRoute: typeof AuthenticatedConsoleKnowledgeRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/intelligence': {
      id: '/_authenticated/console/intelligence'
      path: '/intelligence'
      fullPath: '/console/intelligence'
      preLoaderRoute: typeof AuthenticatedConsoleIntelligenceRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/incidents': {
      id: '/_authenticated/console/incidents'
      path: '/incidents'
      fullPath: '/console/incidents'
      preLoaderRoute: typeof AuthenticatedConsoleIncidentsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/devices': {
      id: '/_authenticated/console/devices'
      path: '/devices'
      fullPath: '/console/devices'
      preLoaderRoute: typeof AuthenticatedConsoleDevicesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/copilot': {
      id: '/_authenticated/console/copilot'
      path: '/copilot'
      fullPath: '/console/copilot'
      preLoaderRoute: typeof AuthenticatedConsoleCopilotRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/audit': {
      id: '/_authenticated/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof AuthenticatedConsoleAuditRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/about': {
      id: '/_authenticated/console/about'
      path: '/about'
      fullPath: '/console/about'
      preLoaderRoute: typeof AuthenticatedConsoleAboutRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/incidents/$incidentId': {
      id: '/_authenticated/console/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/console/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedConsoleIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedConsoleIncidentsRoute
    }
    '/_authenticated/console/devices/$deviceId': {
      id: '/_authenticated/console/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/console/devices/$deviceId'
      preLoaderRoute: typeof AuthenticatedConsoleDevicesDeviceIdRouteImport
      parentRoute: typeof AuthenticatedConsoleDevicesRoute
    }
  }
}

interface AuthenticatedConsoleDevicesRouteChildren {
  AuthenticatedConsoleDevicesDeviceIdRoute: typeof AuthenticatedConsoleDevicesDeviceIdRoute
}

const AuthenticatedConsoleDevicesRouteChildren: AuthenticatedConsoleDevicesRouteChildren =
  {
    AuthenticatedConsoleDevicesDeviceIdRoute:
      AuthenticatedConsoleDevicesDeviceIdRoute,
  }

const AuthenticatedConsoleDevicesRouteWithChildren =
  AuthenticatedConsoleDevicesRoute._addFileChildren(
    AuthenticatedConsoleDevicesRouteChildren,
  )

interface AuthenticatedConsoleIncidentsRouteChildren {
  AuthenticatedConsoleIncidentsIncidentIdRoute: typeof AuthenticatedConsoleIncidentsIncidentIdRoute
}

const AuthenticatedConsoleIncidentsRouteChildren: AuthenticatedConsoleIncidentsRouteChildren =
  {
    AuthenticatedConsoleIncidentsIncidentIdRoute:
      AuthenticatedConsoleIncidentsIncidentIdRoute,
  }

const AuthenticatedConsoleIncidentsRouteWithChildren =
  AuthenticatedConsoleIncidentsRoute._addFileChildren(
    AuthenticatedConsoleIncidentsRouteChildren,
  )

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleAboutRoute: typeof AuthenticatedConsoleAboutRoute
  AuthenticatedConsoleAuditRoute: typeof AuthenticatedConsoleAuditRoute
  AuthenticatedConsoleCopilotRoute: typeof AuthenticatedConsoleCopilotRoute
  AuthenticatedConsoleDevicesRoute: typeof AuthenticatedConsoleDevicesRouteWithChildren
  AuthenticatedConsoleIncidentsRoute: typeof AuthenticatedConsoleIncidentsRouteWithChildren
  AuthenticatedConsoleIntelligenceRoute: typeof AuthenticatedConsoleIntelligenceRoute
  AuthenticatedConsoleKnowledgeRoute: typeof AuthenticatedConsoleKnowledgeRoute
  AuthenticatedConsolePredictionsRoute: typeof AuthenticatedConsolePredictionsRoute
  AuthenticatedConsoleResponsibleAiRoute: typeof AuthenticatedConsoleResponsibleAiRoute
  AuthenticatedConsoleSettingsRoute: typeof AuthenticatedConsoleSettingsRoute
  AuthenticatedConsoleSustainabilityRoute: typeof AuthenticatedConsoleSustainabilityRoute
  AuthenticatedConsoleTopologyRoute: typeof AuthenticatedConsoleTopologyRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleAboutRoute: AuthenticatedConsoleAboutRoute,
  AuthenticatedConsoleAuditRoute: AuthenticatedConsoleAuditRoute,
  AuthenticatedConsoleCopilotRoute: AuthenticatedConsoleCopilotRoute,
  AuthenticatedConsoleDevicesRoute:
    AuthenticatedConsoleDevicesRouteWithChildren,
  AuthenticatedConsoleIncidentsRoute:
    AuthenticatedConsoleIncidentsRouteWithChildren,
  AuthenticatedConsoleIntelligenceRoute: AuthenticatedConsoleIntelligenceRoute,
  AuthenticatedConsoleKnowledgeRoute: AuthenticatedConsoleKnowledgeRoute,
  AuthenticatedConsolePredictionsRoute: AuthenticatedConsolePredictionsRoute,
  AuthenticatedConsoleResponsibleAiRoute:
    AuthenticatedConsoleResponsibleAiRoute,
  AuthenticatedConsoleSettingsRoute: AuthenticatedConsoleSettingsRoute,
  AuthenticatedConsoleSustainabilityRoute:
    AuthenticatedConsoleSustainabilityRoute,
  AuthenticatedConsoleTopologyRoute: AuthenticatedConsoleTopologyRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
