/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleTopologyRouteImport } from './routes/_authenticated/console.topology'
import { Route as AuthenticatedConsoleSustainabilityRouteImport } from './routes/_authenticated/console.sustainability'
import { Route as AuthenticatedConsoleResponsibleAiRouteImport } from './routes/_authenticated/console.responsible-ai'
import { Route as AuthenticatedConsolePredictionsRouteImport } from './routes/_authenticated/console.predictions'
import { Route as AuthenticatedConsoleIntelligenceRouteImport } from './routes/_authenticated/console.intelligence'
import { Route as AuthenticatedConsoleDevicesRouteImport } from './routes/_authenticated/console.devices'
import { Route as AuthenticatedConsoleAboutRouteImport } from './routes/_authenticated/console.about'
import { Route as AuthenticatedConsoleDevicesDeviceIdRouteImport } from './routes/_authenticated/console.devices.$deviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/_authenticated/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTopologyRoute =
  AuthenticatedConsoleTopologyRouteImport.update({
    id: '/topology',
    path: '/topology',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSustainabilityRoute =
  AuthenticatedConsoleSustainabilityRouteImport.update({
    id: '/sustainability',
    path: '/sustainability',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleResponsibleAiRoute =
  AuthenticatedConsoleResponsibleAiRouteImport.update({
    id: '/responsible-ai',
    path: '/responsible-ai',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePredictionsRoute =
  AuthenticatedConsolePredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleIntelligenceRoute =
  AuthenticatedConsoleIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleDevicesRoute =
  AuthenticatedConsoleDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleAboutRoute =
  AuthenticatedConsoleAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleDevicesDeviceIdRoute =
  AuthenticatedConsoleDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => AuthenticatedConsoleDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/console/about': typeof AuthenticatedConsoleAboutRoute
  '/console/devices': typeof AuthenticatedConsoleDevicesRouteWithChildren
  '/console/intelligence': typeof AuthenticatedConsoleIntelligenceRoute
  '/console/predictions': typeof AuthenticatedConsolePredictionsRoute
  '/console/responsible-ai': typeof AuthenticatedConsoleResponsibleAiRoute
  '/console/sustainability': typeof AuthenticatedConsoleSustainabilityRoute
  '/console/topology': typeof AuthenticatedConsoleTopologyRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/devices/$deviceId': typeof AuthenticatedConsoleDevicesDeviceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console/about': typeof AuthenticatedConsoleAboutRoute
  '/console/devices': typeof AuthenticatedConsoleDevicesRouteWithChildren
  '/console/intelligence': typeof AuthenticatedConsoleIntelligenceRoute
  '/console/predictions': typeof AuthenticatedConsolePredictionsRoute
  '/console/responsible-ai': typeof AuthenticatedConsoleResponsibleAiRoute
  '/console/sustainability': typeof AuthenticatedConsoleSustainabilityRoute
  '/console/topology': typeof AuthenticatedConsoleTopologyRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/devices/$deviceId': typeof AuthenticatedConsoleDevicesDeviceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/console/about': typeof AuthenticatedConsoleAboutRoute
  '/_authenticated/console/devices': typeof AuthenticatedConsoleDevicesRouteWithChildren
  '/_authenticated/console/intelligence': typeof AuthenticatedConsoleIntelligenceRoute
  '/_authenticated/console/predictions': typeof AuthenticatedConsolePredictionsRoute
  '/_authenticated/console/responsible-ai': typeof AuthenticatedConsoleResponsibleAiRoute
  '/_authenticated/console/sustainability': typeof AuthenticatedConsoleSustainabilityRoute
  '/_authenticated/console/topology': typeof AuthenticatedConsoleTopologyRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/devices/$deviceId': typeof AuthenticatedConsoleDevicesDeviceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/console/about'
    | '/console/devices'
    | '/console/intelligence'
    | '/console/predictions'
    | '/console/responsible-ai'
    | '/console/sustainability'
    | '/console/topology'
    | '/console/'
    | '/console/devices/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console/about'
    | '/console/devices'
    | '/console/intelligence'
    | '/console/predictions'
    | '/console/responsible-ai'
    | '/console/sustainability'
    | '/console/topology'
    | '/console'
    | '/console/devices/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/console'
    | '/_authenticated/console/about'
    | '/_authenticated/console/devices'
    | '/_authenticated/console/intelligence'
    | '/_authenticated/console/predictions'
    | '/_authenticated/console/responsible-ai'
    | '/_authenticated/console/sustainability'
    | '/_authenticated/console/topology'
    | '/_authenticated/console/'
    | '/_authenticated/console/devices/$deviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/topology': {
      id: '/_authenticated/console/topology'
      path: '/topology'
      fullPath: '/console/topology'
      preLoaderRoute: typeof AuthenticatedConsoleTopologyRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/sustainability': {
      id: '/_authenticated/console/sustainability'
      path: '/sustainability'
      fullPath: '/console/sustainability'
      preLoaderRoute: typeof AuthenticatedConsoleSustainabilityRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/responsible-ai': {
      id: '/_authenticated/console/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/console/responsible-ai'
      preLoaderRoute: typeof AuthenticatedConsoleResponsibleAiRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/predictions': {
      id: '/_authenticated/console/predictions'
      path: '/predictions'
      fullPath: '/console/predictions'
      preLoaderRoute: typeof AuthenticatedConsolePredictionsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/intelligence': {
      id: '/_authenticated/console/intelligence'
      path: '/intelligence'
      fullPath: '/console/intelligence'
      preLoaderRoute: typeof AuthenticatedConsoleIntelligenceRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/devices': {
      id: '/_authenticated/console/devices'
      path: '/devices'
      fullPath: '/console/devices'
      preLoaderRoute: typeof AuthenticatedConsoleDevicesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/about': {
      id: '/_authenticated/console/about'
      path: '/about'
      fullPath: '/console/about'
      preLoaderRoute: typeof AuthenticatedConsoleAboutRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/devices/$deviceId': {
      id: '/_authenticated/console/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/console/devices/$deviceId'
      preLoaderRoute: typeof AuthenticatedConsoleDevicesDeviceIdRouteImport
      parentRoute: typeof AuthenticatedConsoleDevicesRoute
    }
  }
}

interface AuthenticatedConsoleDevicesRouteChildren {
  AuthenticatedConsoleDevicesDeviceIdRoute: typeof AuthenticatedConsoleDevicesDeviceIdRoute
}

const AuthenticatedConsoleDevicesRouteChildren: AuthenticatedConsoleDevicesRouteChildren =
  {
    AuthenticatedConsoleDevicesDeviceIdRoute:
      AuthenticatedConsoleDevicesDeviceIdRoute,
  }

const AuthenticatedConsoleDevicesRouteWithChildren =
  AuthenticatedConsoleDevicesRoute._addFileChildren(
    AuthenticatedConsoleDevicesRouteChildren,
  )

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleAboutRoute: typeof AuthenticatedConsoleAboutRoute
  AuthenticatedConsoleDevicesRoute: typeof AuthenticatedConsoleDevicesRouteWithChildren
  AuthenticatedConsoleIntelligenceRoute: typeof AuthenticatedConsoleIntelligenceRoute
  AuthenticatedConsolePredictionsRoute: typeof AuthenticatedConsolePredictionsRoute
  AuthenticatedConsoleResponsibleAiRoute: typeof AuthenticatedConsoleResponsibleAiRoute
  AuthenticatedConsoleSustainabilityRoute: typeof AuthenticatedConsoleSustainabilityRoute
  AuthenticatedConsoleTopologyRoute: typeof AuthenticatedConsoleTopologyRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleAboutRoute: AuthenticatedConsoleAboutRoute,
  AuthenticatedConsoleDevicesRoute:
    AuthenticatedConsoleDevicesRouteWithChildren,
  AuthenticatedConsoleIntelligenceRoute: AuthenticatedConsoleIntelligenceRoute,
  AuthenticatedConsolePredictionsRoute: AuthenticatedConsolePredictionsRoute,
  AuthenticatedConsoleResponsibleAiRoute:
    AuthenticatedConsoleResponsibleAiRoute,
  AuthenticatedConsoleSustainabilityRoute:
    AuthenticatedConsoleSustainabilityRoute,
  AuthenticatedConsoleTopologyRoute: AuthenticatedConsoleTopologyRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
